# policy/opa-config.yaml
#
# ===========================
# Security & Ops
# ===========================
# - Runs OPA as an external authz gRPC server for Envoy.
# - Fail CLOSED at Envoy if OPA is unreachable/timeouts (see Envoy config).
# - Decision logs are enabled for audit/forensics; ship to your SIEM.
# - Use bundles to version/pin policy; verify bundle signatures (e.g., with TUF/sigstore).
#
# ===========================
# Tunables / Config
# ===========================
# - plugins.envoy_ext_authz_grpc.query: decision path to evaluate per request.
# - bundles: pull from local FS (for PoC) or a remote HTTPS registry with auth.
# - services: configure CA pinning and mTLS to the bundle server in prod.
#
# ===========================
# Improvements / Production
# ===========================
# - Enable bundle signatures and pin signing keys.
# - Add status/health reporting to alert on stale policy.
# - Use `decision_logs` with TLS+mTLS to a centralized collector.

services:
  # For remote bundles, define one or more services with TLS/mTLS and auth.
  # Example (commented out):
  # bundlesvc:
  #   url: https://opa-bundles.internal.yourco
  #   credentials:
  #     bearer:
  #       token: ${OPA_BUNDLE_TOKEN}

bundles:
  # Local file-system bundle for PoC (mounted into /policy/bundles)
  # In prod, point to "bundlesvc" above and provide a signed bundle.
  kms_receipt:
    service: ""
    resource: file:///policy/bundles/kms_receipt.tar.gz
    polling:
      min_delay_seconds: 5
      max_delay_seconds: 10

# Envoy external authz gRPC plugin
plugins:
  envoy_ext_authz_grpc:
    addr: :9191
    # The Rego entrypoint (must exist in your bundle)
    query: data.combined.allow
    # Include the full set of headers so policy can read Authorization and x-kms-sig/x-kms-key
    # (Envoy will forward headers by default; you may also whitelist in Envoy for hardening.)
    enable_reflection: false

# Decision logs for audit/forensics (example: local file; in prod ship to SIEM)
decision_logs:
  console: true

# Status endpoint to detect stale bundles
status:
  console: true