# -------------------------------------------------------------------
# File: sign-csf.tf
# -------------------------------------------------------------------
# Purpose:
#   Requests a signed client certificate from Vault's intermediate PKI
#   mount for Kubernetes client authentication. This is typically used
#   to authenticate `kubectl` users with mutual TLS (mTLS).
#
# Inputs:
#   - `yubikey.csr`: Base64-encoded certificate signing request (CSR)
#       generated by the user's YubiKey or local keypair.
#
# Vault Path:
#   - `pki-int/issue/kubernetes-client` issues certificates for the
#     `kubernetes-client` role in the intermediate PKI backend.
#
# Security Notes:
#   - The issued certificate is valid for 24 hours.
#   - Private key remains on the YubiKey or in secure storage.
# -------------------------------------------------------------------
data "vault_generic_endpoint" "client_cert" {
  path = "pki-int/issue/kubernetes-client"

  data_json = jsonencode({
    common_name = "kubectl-user"
    ttl         = "24h"
    csr         = filebase64("yubikey.csr")
  })
}
