permissions:
  contents: read
  packages: write   # only where image push is required; remove in workflows that don't push
  
name: frost-ci
on:
  push:
    branches: ["poc", "poc/**"]
    paths:
      - "frost/**"
      - "k8s/frost/**"
  pull_request:
    branches: ["poc", "poc/**"]
    paths:
      - "frost/**"
      - "k8s/frost/**"
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/frost:latest frost
      - name: Push image
        env:
          CR_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${CR_PAT}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/${{ github.repository_owner }}/frost:latest
  deploy-k8s:
    if: ${{ secrets.KUBE_CONFIG != '' }}
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-kubectl@v4
      - name: Write kubeconfig
        run: echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
      - name: Apply manifests
        run: |
          kubectl apply -f k8s/frost/namespace.yaml
          kubectl apply -f k8s/frost/secrets.example.yaml
          kubectl apply -f k8s/frost/daemonset.yaml
          kubectl apply -f k8s/frost/service.yaml
          kubectl apply -f k8s/frost/coordinator.yaml
