# -----------------------------------------------------------------------------
# File: .github/workflows/poc-ci.yml
# What it does:
#   CI for the **proof-of-concept** branch only. Validates proto generation,
#   installs deps, and builds Docker images for all services.
#
# Security & Ops notes:
#   - Pin action SHAs in high-security environments.
#   - Consider pip-audit and Trivy/Grype scans on images.
#   - Use OIDC to authenticate to OCI/GHCR if you push images.
#
# Trigger:
#   - Only on branch 'poc' (rename below if you use a different POC branch).
# -----------------------------------------------------------------------------
name: poc-ci

on:
  push:
    branches: [ "poc" ]
  pull_request:
    branches: [ "poc" ]


# ✅ Least-privilege token for the whole workflow (satisfies CKV2_GHA_1)
permissions:
  contents: read       # checkout needs only read
  # Add more only if needed:
  # id-token: write    # enable if using OIDC to push images / fetch cloud creds
  # packages: write    # enable if pushing to GHCR
  # actions: read
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate protobufs
        run: |
          python -m grpc_tools.protoc -I proto proto/mpc.proto --python_out=gen --grpc_python_out=gen

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker build (Coordinator)
        run: docker build -f Dockerfile.coordinator -t mpc-coordinator:ci .
      - name: Docker build (CA)
        run: docker build -f Dockerfile.ca -t mpc-ca:ci .
      - name: Docker build (TLog)
        run: docker build -f Dockerfile.tlog -t mpc-tlog:ci .
      - name: Docker build (Auth)
        run: docker build -f Dockerfile.auth -t mpc-auth:ci .
