apiVersion: v1
kind: ConfigMap
metadata:
  name: dex-config
data:
  config.yaml: |
    issuer: http://localhost:5556/dex
    storage:
      type: memory
    web:
      http: 0.0.0.0:5556
    grpc:
      addr: 0.0.0.0:5557
    staticClients:
    - id: vault
      redirectURIs:
      - 'http://127.0.0.1:8250/oidc/callback'
      name: 'Vault OIDC'
      secret: vault-secret
    connectors:
    - type: oidc
      id: yubico
      name: YubiKey FIDO2
      config:
        issuer: https://auth.yubico.com/
        clientID: <YUBICO_CLIENT_ID>
        clientSecret: <YUBICO_CLIENT_SECRET>
        scopes: ["openid", "email", "profile"]
